[package]
name = "taglib-rs"
version = "0.1.0"
authors = ["Adam Harries <harries.adam@gmail.com>"]

[lib]
name = "taglib"
path = "src/lib.rs"

[dependencies.taglib-sys]
path = "taglib-sys"
version = "0.1.0"

[dependencies]
libc = "0.2"