[package]
name = "taglib-sys"
version = "0.1.0"
authors = ["Adam Harries <harries.adam@gmail.com>"]
links = "tag_c"
build="build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.37.0"
cmake = "0.1.31"
